### ISSUE TITLE
[ ART REQUEST ] - Aubrey Outfit OMORI

### ISSUE THREAD

**Issue by VendixDilan** [Just-Natsuki-Team/NatsukiModOutfits#8]
# Context:
I think Natsuki and Aubrey have a lot in common, not only style-wise but also with her character. So I think a lot of people would be interested in having Aubrey's clothes in the game! She already has the pink hair, so why not add the rest?

## Assets needed:
Aubrey's bow
Aubrey's clothes

## Caveats:
I again don't know if there will be any issues with the headgear, the clothes should be fine though.

**Comment by RaionArt** [comment]
Thank you for your suggestion! 
The outfit will be added in v1.3.
